version: '3'
services:
  ubuntu:
    build: ./ubuntu
    restart: 'no'
    ports:
      - '${APACHE_PORT}:80'
    volumes:
      - '../:/var/www'
      - './php/php.ini:/etc/php/7.3/apache2/php.ini'
      - './php/php.ini:/etc/php/7.3/cli/php.ini'
      - './apache2/apache2.conf:/etc/apache2/apache2.conf'
      - './apache2/ports.conf:/etc/apache2/ports.conf'
      - './apache2/000-default.conf:/etc/apache2/sites-enabled/000-default.conf'
    links:
      - psql
  psql:
    image: 'postgres:9.6.19'
    restart: 'no'
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - './psql/data:/var/lib/postgresql/data'
    environment: 
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'